name: firetracer
on:
  push:
    branches: [ main ]
jobs:
  secrets_in_github_actions:
    runs-on: ubuntu-latest
    steps:
      - name: run test | 
        env:
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run : |
          php ../../src/includes/database.php
