name: firetracer
on:
  push:
    branches: [ main ]
jobs:
  secrets_in_github_actions:
    steps:
      - name: run test
      env:
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run : |
        echo "secrets ok"
